---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Workflow Attestation Test"

on:
  push:

jobs:
  build:
    name: "Secure CI Framework"
    runs-on: "ubuntu-latest"
    # runs-on: "anzx-default-np"
    permissions:
      id-token: "write"
      packages: "write"
      contents: "read"
      attestations: "write"
    env:
      REGISTRY: "ghcr.io"
      IMAGE_NAME: "hello-world"
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Pull and retag alpine"
        run: |
          docker pull alpine:latest
          docker tag alpine:latest ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
          image_digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest | grep -oP '(?<=sha256:)\w+')
          echo "IMAGE_DIGEST=${image_digest}" >> $GITHUB_ENV          
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'
      - name: Attest SBOM
        uses: actions/attest-sbom@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          subject-digest: sha256:${{ env.IMAGE_DIGEST }}
          sbom-path: 'sbom.spdx.json'
          push-to-registry: true
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          subject-digest: sha256:${{ env.IMAGE_DIGEST }}
          push-to-registry: true
      - name: Test
        run: |
          curl -s http://localhost:5000/v2/${{ env.IMAGE_NAME }}/tags/list | jq . || true
          # cat sbom.spdx.json
